apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.deployment.name }}-ingress-route
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: HostRegexp(`.+`)
    priority: 10
    middlewares:
    - name: custom-errors-redirect
      namespace: {{ .Release.Namespace }}
    services:
    - kind: Service
      name: {{ .Values.deployment.name }}-svc
      port: {{ .Values.container.port }}
  tls:
    secretName: cluster-sololab-one-production-tls
