apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.container.port }}
    targetPort: {{ .Values.container.port }}
    protocol: TCP
  selector:
    app: {{ .Values.deployment.name }}