apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ include "using.port" . }} 
    targetPort: {{ include "using.port" . }} 
    protocol: TCP
  selector:
    app: {{ .Values.deployment.name }}